---

- name: Configure VXLAN
  hosts: leaf
  gather_facts: no
  connection: local
  vars_files:
    - vars_files/vlans.yml
    - vars_files/vrfs.yml

  tasks:
    - name: Configure L2 VXLAN
      tags:
        - l2vxlan
      eos_config:
        src: l2vxlan_config.j2

    - name: Delete L2 VXLAN
      tags:
        - deletel2
      eos_config:
        src: delete_l2vxlan.j2

    - name: Configure L3 VXLAN
      tags:
        - l3vxlan
      eos_config:
        src: l3vxlan_config.j2

    - name: Delete L3 VXLAN
      tags:
        - deletel3
      eos_config:
        src: delete_l3vxlan.j2

    - name: Save running-config to startup-config if modified
      tags:
        - l2vxlan
        - l3vxlan
        - deletel2
        - deletel3
      eos_config:
        save_when: changed

    - name: Verify Configuration Changes
      tags:
        - l2vxlan
        - l3vxlan
        - deletel2
        - deletel3
      eos_command:
        commands: "show vxlan vni | json"
      register: sh_vni

    - name: Display "show vxlan vni" output
      tags:
        - l2vxlan
        - l3vxlan
        - deletel2
        - deletel3
      debug:
        msg: "VNI Configuration: {{sh_vni['stdout_lines'][0]}}"