---

- name: Configuration Backup
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Backup all running-configs
      eos_config:
        backup: yes
      register: backup_eos_location
