---

- name: Upgrade EOS
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Collecting Facts
      tags:
        - collect_facts
      eos_facts:
        gather_subset: all


    - name: Verify current EOS image against target revision
      tags:
        - verify_facts
      set_fact:
        upgrade_verification={{ target_rev > ansible_net_version }}


    - name: EOS image upload, and install
      tags:
        - image_install
      eos_command:
        commands:
          - 'install source {{ url }} destination {{ file_name }} now'
      when: upgrade_verification


    - name: Reboot switch(es) for new EOS image to take effect
      tags:
        - reboot_sw
      eos_command:
        commands:
          - 'reload now'
      when: upgrade_verification


    - name: Waiting for switch to come back online
      wait_for: 
        host: '{{ inventory_hostname }}'
        port: 22
        delay: 120
        sleep: 1
        timeout: 900
      delegate_to: localhost
      when: upgrade_verification


    - name: Collecting post upgrade facts
      tags:
        - post_install_facts
      eos_facts:
        gather_subset: all

   
    - name: Verify EOS revision matches {{ target_rev }}
      assert:
        that:
          - target_rev == ansible_net_version