---

- name: Configure VLAN
  hosts: leaf
  gather_facts: no
  connection: local

  tasks:
    - name: Configure VLAN 
      eos_config:
        lines:
          - "name ansible-test"
        parents:
          - vlan 1812
    
    - name: Verfiy VLAN Configuration
      eos_command:
        commands:
          - show vlan 1812
        wait_for:
          - result[0] contains 1812
      register: output

    - name: Print the output
      debug:
        var: output
