#!/usr/bin/python

import sys, getpass
from jsonrpclib import Server

user = str(raw_input("Username: "))
passwd = getpass.getpass()
input_string = str(raw_input("What host or hosts would you like to connect to separated by a comma: "))
host = input_string.split(",")

def main():
    try:
        for a in host:
            cmdapi = Server("http://%s:%s@%s/command-api" % (user,passwd,a))
            summ = cmdapi.runCmds(1,["show ip bgp summary"])

            for b in summ[0]['vrfs']['default']['peers']:
                peers = summ[0]['vrfs']['default']['peers'][b]
                state = summ[0]['vrfs']['default']['peers'][b]['peerState']
                prfxrcvd = summ[0]['vrfs']['default']['peers'][b]['prefixReceived']
                asnum = summ[0]['vrfs']['default']['peers'][b]['asn']
                updown = summ[0]['vrfs']['default']['peers'][b]['upDownTime']
            
                print "\t######### BGP stats for %s #################" % a
                print "\tPeer IP Address: %s" % b
                print "\tPeer State: %s" % state
                print "\tPrefixes Received: %s" % prfxrcvd
                print "\tAS Number: %s" % asnum
                print "\tUP/Down Time: %s\n" % updown

    except:
        sys.exit(2)

if __name__ == '__main__':
    main()
