---

- name: Create a container topology
  hosts: cvp_server
  gather_facts: no
  collections:
    - arista.cvp
  
  vars:
    verbose: False
    containers_provision:
      SJC:
        parent_container: Tenant
      Spines-SJC:
        parent_container: SJC
        devices:
          - dm1-263sw21
          - dm1-263sw22
      Leaves-SJC-StandAlone:
        parent_container: SJC
        devices:
          - dm1-262sw39
      Leaves-SJC-MLAG:
        parent_container: SJC
        devices:
          - dm1-262sw37
          - dm1-262sw38
      Hosts-SJC:
        parent_container: SJC
        devices:
          - dm1-262sw35
          - dm1-262sw40

  tasks:
  - name: "Retrieve CVP facts from {{ inventory_hostname }}"
    cv_facts:
    register: cvp_facts
    tags:
      - always

  - name: "Build container topology on {{ inventory_hostname }}"
    tags:
      - provision
    cv_container:
      topology: '{{ containers_provision }}'
      cvp_facts: '{{ cvp_facts.ansible_facts }}'
      save_topology: true
      mode: 'merge'
    register: cv_container

  - name: "Print cv_container output"
    debug:
      msg: "{{ cv_container }}"