---

- name: Create a container topology
  hosts: cvp_server
  gather_facts: no
  collections:
    - arista.cvp

  vars:
    verbose: False
    containers_provision:
      SE-LAB:
        parent_container: Vantage-Lab
      SuperSpine:
        parent_container: SE-LAB
        devices:
          - superspine1
          - superspine2
      Spine:
        parent_container: SE-LAB
        devices:
          - spine1
          - spine2
          - spine3
      Leaves:
        parent_container: SE-LAB
        devices:
          - leaf1r1
          - leaf2r1
          - leaf1r2
          - leaf2r2

  tasks:
  - name: "Retrieve CVP facts from {{ inventory_hostname }}"
    cv_facts:
    register: cvp_facts
    tags:
      - always

  - name: "Build container topology on {{ inventory_hostname }}"
    tags:
      - provision
    cv_container:
      topology: '{{ containers_provision }}'
      cvp_facts: '{{ cvp_facts.ansible_facts }}'
      mode: 'merge'
    register: cv_container

  - name: "Print cv_container output"
    debug:
      msg: "{{ cv_container }}"